version: '2.1'
services:
  ldap:
    image: osixia/openldap:1.1.9
    restart: "no"
    hostname: ldap
    environment:
      HOSTNAME: "ldap"
      LDAP_LOG_LEVEL: "0"
      LDAP_ORGANISATION: "SETEC/SR/PF/RS"
      LDAP_DOMAIN: "setecrs.dpf.gov.br"
      LDAP_BASE_DN: "dc=setecrs,dc=dpf,dc=gov,dc=br"
      LDAP_ADMIN_PASSWORD: "TESTPASSWORD"
      LDAP_CONFIG_PASSWORD: "TESTPASSWORD"
      LDAP_READONLY_USER: "false"
      #LDAP_READONLY_USER_USERNAME: "readonly"
      #LDAP_READONLY_USER_PASSWORD: "readonly"
      LDAP_RFC2307BIS_SCHEMA: "false"
      LDAP_BACKEND: "hdb"
      LDAP_TLS: "true"
      LDAP_TLS_CRT_FILENAME: "ldap.crt"
      LDAP_TLS_KEY_FILENAME: "ldap.key"
      LDAP_TLS_CA_CRT_FILENAME: "ca.crt"
      LDAP_TLS_ENFORCE: "false"
      LDAP_TLS_CIPHER_SUITE: "SECURE256:-VERS-SSL3.0"
      LDAP_TLS_PROTOCOL_MIN: "3.1"
      LDAP_TLS_VERIFY_CLIENT: "demand"
      KEEP_EXISTING_CONFIG: "false"
      LDAP_REMOVE_CONFIG_AFTER_SETUP: "true"
      LDAP_SSL_HELPER_PREFIX: "ldap"
      LDAP_BASE_DN: "dc=setecrs,dc=dpf,dc=gov,dc=br"
    expose:
      - 389
      - 636
  api:
    build: sard-admin
    restart: "always"
    depends_on:
      - ldap
    links:
      - ldap
    environment:
      SID: "S-1-5-21-682337471-1126014868-3524221000"
      LDAP_BASE_DN: "dc=setecrs,dc=dpf,dc=gov,dc=br"
      LDAP_ADMIN_PASSWORD: "TESTPASSWORD"
      LDAP_SERVER: "ldap"
      JWT_SECRET: "JWT_SECRET"
      LANG: "en_US.UTF-8"
      FLASK_APP: "sardadmin"
      FLASK_ENV: "development"
    volumes:
      - ./sard-admin/:/app/
    ports:
      - 8082:80
    command: ['flask', 'run', '-h', '0.0.0.0', '-p', '80']
  ui:
    build: sard-admin-ui
    restart: "always"
    depends_on:
      - ldap
      - api
    links:
      - ldap
      - api
    environment:
      SARD_ADMIN_SERVICE_HOST: "api"
      SARD_ADMIN_SERVICE_PORT: 80
      WEKAN_GRAPHQL_NOAUTH_SERVICE_HOST: "api"
      WEKAN_GRAPHQL_NOAUTH_SERVICE_PORT: 80
      LOCKER_SERVICE_HOST: "api"
      LOCKER_SERVICE_PORT: 80
      LANG: "en_US.UTF-8"
    ports:
      - 8081:80
